[package]
name = "nes_emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.6.1"
enumflags2 = "0.7.7"
lazy_static = "1.4.0"

sdl2 = "0.34.0"
rand = "=0.7.3"
